### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by tbuchannan** [tbuchannan/skynet#2]
## Mod
- [ ] Move Mass Unban to mod cog
- [ ] Add login/logout command
- [ ] Refactor clear command
- [ ] Add Info Command
- [ ] Add Tribunal Summon

## Fun
- [ ] Add anime/manga list
- [ ] box raid
